- hosts: webservers
  tasks:
  - apt:
      name: apache2
      state: present
  - copy:
      src: ports.conf.tmpl
      dest: /etc/apache2/ports.conf
    notify: restart apache2
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted



      
